# Generated by Django 3.1.3 on 2020-11-28 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('nom_Categoria', models.CharField(max_length=30, unique=True)),
                ('cod_Categoria', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nom_Cliente', models.CharField(max_length=80)),
                ('tel_Cliente', models.CharField(max_length=15)),
                ('correo_Cliente', models.EmailField(max_length=100)),
                ('ID_dni', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Producto', models.CharField(max_length=30)),
                ('pre_Producto', models.IntegerField(default=0)),
                ('ven_Realizada', models.BooleanField(default=False)),
                ('uni_St_Producto', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_1.categoriasproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDueño', models.CharField(max_length=100)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dueño', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
